-- 년, 월, 성별 별 상품 구 회원 수 구하기.sql

-- Oracle JOIN
SELECT TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR
     , EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH
     , I.GENDER
     , COUNT(DISTINCT I.USER_ID) AS USERS
  FROM USER_INFO I
     , ONLINE_SALE S
 WHERE I.USER_ID = S.USER_ID
   AND I.GENDER IS NOT NULL
 GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY')
        , EXTRACT(MONTH FROM S.SALES_DATE)
        , I.GENDER
 ORDER BY YEAR ASC, MONTH ASC, GENDER ASC

 -- ANSI JOIN
 SELECT TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR
     , EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH
     , I.GENDER
     , COUNT(DISTINCT I.USER_ID) AS USERS
  FROM USER_INFO I
  JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
 WHERE I.GENDER IS NOT NULL
 GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY')
        , EXTRACT(MONTH FROM S.SALES_DATE)
        , I.GENDER
 ORDER BY YEAR ASC, MONTH ASC, GENDER ASC