-- 5월 식품들의 총매출 조회하기.sql

-- Oracle JOIN
SELECT A.PRODUCT_ID
     , A.PRODUCT_NAME
     , B.SUM_AMOUNT * A.PRICE AS TOTAL_SALES
  FROM FOOD_PRODUCT A
     , (
        SELECT PRODUCT_ID
             , SUM(AMOUNT) AS SUM_AMOUNT
          FROM FOOD_ORDER
         WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
         GROUP BY PRODUCT_ID 
       ) B
 WHERE A.PRODUCT_ID = B.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC


 -- ANSI JOIN
 SELECT A.PRODUCT_ID
     , A.PRODUCT_NAME
     , B.SUM_AMOUNT * A.PRICE AS TOTAL_SALES
  FROM FOOD_PRODUCT A
  JOIN (
        SELECT PRODUCT_ID
             , SUM(AMOUNT) AS SUM_AMOUNT
          FROM FOOD_ORDER
         WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
         GROUP BY PRODUCT_ID 
       ) B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC