-- 그룹별 조건에 맞는 식당 목록 출력하기.sql

-- Orale join
SELECT P.MEMBER_NAME
     , R.REVIEW_TEXT
     , TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
  FROM MEMBER_PROFILE P
     , REST_REVIEW R
     , (
        SELECT MEMBER_ID
             , COUNT(REVIEW_ID) AS REVIEW_CNT
             , RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) AS RANK
          FROM REST_REVIEW
         GROUP BY MEMBER_ID
       ) A
   WHERE P.MEMBER_ID = R.MEMBER_ID
     AND R.MEMBER_ID = A.MEMBER_ID
     AND A.RANK = 1
   ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC

-- ANSI join
SELECT P.MEMBER_NAME
     , R.REVIEW_TEXT
     , TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
  FROM MEMBER_PROFILE P
  JOIN REST_REVIEW R
    ON P.MEMBER_ID = R.MEMBER_ID
  JOIN (
        SELECT MEMBER_ID
             , COUNT(REVIEW_ID) AS REVIEW_CNT
             , RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) AS RANK
          FROM REST_REVIEW
         GROUP BY MEMBER_ID
       ) A
    ON R.MEMBER_ID = A.MEMBER_ID
  WHERE A.RANK = 1
  ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC