-- 취소되지 않은 진료 예약 조회하기.sql

-- Oracle JOIN
SELECT A.APNT_NO
     , P.PT_NAME
     , A.PT_NO
     , A.MCDP_CD
     , D.DR_NAME
     , A.APNT_YMD
  FROM PATIENT P
     , DOCTOR D
     , APPOINTMENT A
 WHERE TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
   AND A.APNT_CNCL_YN = 'N'
   AND A.MCDP_CD = 'CS'
   AND P.PT_NO = A.PT_NO
   AND D.DR_ID = A.MDDR_ID
 ORDER BY A.APNT_YMD ASC


-- ANSI JOIN
SELECT A.APNT_NO
     , P.PT_NAME
     , A.PT_NO
     , A.MCDP_CD
     , D.DR_NAME
     , A.APNT_YMD
  FROM APPOINTMENT A
  JOIN DOCTOR D
    ON A.MDDR_ID = D.DR_ID
  JOIN PATIENT P
    ON P.PT_NO = A.PT_NO
 WHERE TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
   AND A.APNT_CNCL_YN = 'N'
   AND A.MCDP_CD = 'CS'
 ORDER BY A.APNT_YMD ASC