-- 입양 시각 구하기(1)
SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
     , COUNT(TO_CHAR(DATETIME, 'HH')) AS COUNT
  FROM ANIMAL_OUTS
 WHERE TO_CHAR(DATETIME, 'HH24') BETWEEN '09' AND '19'
 GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
 ORDER BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) ASC