-- 오랜 기간 보호한 동물(1).sql
SELECT I.NAME
     , I.DATETIME
  FROM ANIMAL_INS I
     , ANIMAL_OUTS O
 WHERE I.ANIMAL_ID = O.ANIMAL_ID(+)
   AND O.ANIMAL_ID IS NULL
 ORDER BY I.DATETIME ASC
 FETCH FIRST 3 ROWS ONLY