-- 오랜 기간 보호한 동물(2).sql

-- Oracle 문법
-- SELECT O.ANIMAL_ID
--      , O.NAME
--   FROM ANIMAL_INS I
--      , ANIMAL_OUTS O
--  WHERE I.ANIMAL_ID = O.ANIMAL_ID
--  ORDER BY (O.DATETIME - I.DATETIME) DESC
--  FETCH FIRST 2 ROWS ONLY
 
-- ANSI
SELECT O.ANIMAL_ID
     , O.NAME
  FROM ANIMAL_INS I
  JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
 ORDER BY (O.DATETIME - I.DATETIME) DESC
 FETCH FIRST 2 ROWS ONLY