-- 카테고리 별 도서 판매량 집계하기.sql
SELECT B.CATEGORY
     , SUM(S.SALES) AS TOTAL_SALES
  FROM BOOK B
  JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
--  WHERE TO_CHAR(S.SALES_DATE, 'YYYYMMDD') BETWEEN '20220101' AND '20220131'
 WHERE TO_CHAR(S.SALES_DATE, 'YYYYMM') = '202201'
 GROUP BY B.CATEGORY
 ORDER BY B.CATEGORY ASC